{
  "version": 2,
  "builds": [
    {
      "src": "server.js",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/api/food/(.*)",
      "dest": "/api/food/$1"
    },
    {
      "src": "/api/user/(.*)",
      "dest": "/api/user/$1"
    },
    {
      "src": "/api/cart/(.*)",
      "dest": "/api/cart/$1"
    },
    {
      "src": "/api/order/(.*)",
      "dest": "/api/order/$1"
    },
    {
      "src": "/images/(.*)",
      "dest": "/uploads/$1"
    },
    {
      "src": "/(.*)",
      "dest": "/"
    }
  ]
}
